model: yolov5m
classes: ''
dataset_path: ../deepstack
hyp: data/hyp.scratch.yaml
epochs: 600
batch_size: 16
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
workers: 8
project: train-runs/deepstack
name: RMRR
exist_ok: true
cfg: .\models\yolov5m.yaml
weights: yolov5m.pt
data:
  train: ../deepstack\train
  val: ../deepstack\test
  nc: 75
  names:
  - pig
  - raccoon
  - coyote
  - squirrel
  - bird_bluejay
  - bird_cardinal
  - bird_vulture
  - buffalo
  - bunny
  - cat_black
  - cat_grey
  - cat_orange
  - cat_tort
  - cat_calico
  - cow
  - dog_black_lab
  - dog_pyr
  - snake
  - spider
  - deer
  - opossum
  - scorpion
  - turtle
  - lizard
  - us-plate
  - mercedesbenz
  - amazon
  - prime
  - smile
  - ups
  - fedex
  - bird_crow
  - fox
  - bird_humming
  - dave
  - box_nutrisystem
  - Ryder
  - licence-plate
  - kia
  - budget
  - us-mail
  - truck_trash
  - acdi
  - bird_vireo
  - bird_dove
  - bird_chickadee
  - bird_sparrow
  - bird_titmouse
  - bird_robin
  - moth
  - ryder
  - van
  - suv
  - truck_pickup
  - trailer
  - dog_shepherd
  - car
  - truck
  - person
  - bicycle
  - ford
  - motorcycle
  - bus
  - truck_mixer
  - camper
  - box_closed
  - cart
  - gate
  - ram
  - aqua
  - spectrum
  - lexus
  - chevy
  - cat_white
  - ''
total_batch_size: 16
world_size: 1
global_rank: -1
save_dir: train-runs\deepstack\RMRR
